# Configuration for connecting to the CV Attendant IVR app

tropo:
    # The default voice to use for Speech Synthesis/TTS
    # Refer to: https://www.tropo.com/docs/scripting/say.htm (voice option) for a list of supported voices
    voice: kate
    # The default recognizer to use for Speech Recogintion/ASR
    # Refer to: https://www.tropo.com/docs/scripting/ask.htm (recognizer option) for a list of supported recognizers
    recognizer: en-us
    # The SIP address to send the session/call to if AGItate may not connect to your AGI server
    # this may be another Tropo app that plays a simple message, or an address on your Asterisk server
    # by default, if left unchanged this will play a message to the user:
    #   'We were unable to connect to your A G I server. Please try again later. Goodbye.' 
    next_sip_uri: sip:9991443146@sip.tropo.com
    
agi:
    # This should be your running AGI Server (Adhearsion, PHPAGI, Asterisk-Java, etc)
    uri: agi://cvnet.radishsystems.com:4573/CVAutoAttendant
    # Used for local testing
    uri_for_local_tests: agi://zion:4573/CVAutoAttendant

asterisk:
    sounds:
        enabled: true
        language: en
        # available_files/base_uri does not need to change, unless you want to pull sound files from your own account
        # these files are accessible from the Tropo-AGI/49767 account to yours
        available_files: http://cvnet.radishsystems.com/ChoiceView/ivr/sounds/asterisk_sounds.json
        base_uri: http://cvnet.radishsystems.com/ChoiceView/ivr/sounds